#!/bin/bash


if [ $#==0 ]
then
    echo "
GITSYNC LIGHT VERSION: Current Directory only

usage: gitsync <commit message(muti words OK)>

Gitsync is a tool to help you automatically commit in github.
The first argument passed should be the path, relative to the base path.

Your base path is: $BASE_PATH

You can configure the base path in the source of this command.

To commit, enter gitsync, and then 't' for the current directrory, or a directory path(without spaces). 
All parameters after the first will be combined into the git commit message. The spaces will be kept."
 fi
params = $*
echo “$params”
git status
git add --all .
git commit -m “$params”
git push
echo "github sync sucussful"

exit 1