#!/bin/bash


if [ $#==0 ]
then
    echo "
GITSYNC LIGHT VERSION: current directory only

Usage: gitsync <commit message (multiple words OK)>

Gitsync is a tool to help you automatically commit in GitHub.
The first argument passed should be the path, relative to the base path.

Your base path is: $BASE_PATH

You can configure the base path in the source of this command.

To commit, enter gitsync, and then a commit message. All parameters will be combined into the git commit message. The spaces will be kept."
 fi

echo $*
git status
git add --all .
git commit -m "$*"
git push
echo "github sync successful"

exit 1
